export const manageFollowUpTool=Object.freeze({id:'builtin:manage_follow_up',name:'manage_follow_up',type:'internal_follow_up',
  description:'Schedule or cancel a callback/reminder for the current caller on their current phone number. Interpret duration and consent using the agent prompt. For clear relative requests supply delayMinutes as a number and callerConfirmed=true; no evidence quote or additional caller confirmation is needed. Do not supply localDate/localTime for relative durations. The runtime records the current caller message. Absolute times and cancellations retain their existing evidence/confirmation flow. No caller-provided phone or company identifiers are accepted. A scheduled=false result means explain failure or clarify genuinely missing information; never promise an unsaved follow-up.',
  configuration:{inputSchema:{type:'object',additionalProperties:false,required:['action'],properties:{
    action:{type:'string',enum:['schedule','confirm','cancel']},evidence:{type:'string',minLength:1,maxLength:2000},
    kind:{type:'string',enum:['callback','reminder']},purpose:{type:'string',minLength:1,maxLength:2000},
    delayMinutes:{type:'number',minimum:0.5,maximum:43200},
    callerConfirmed:{type:'boolean'},
    localDate:{type:'string',pattern:'^\\d{4}-\\d{2}-\\d{2}$'},localTime:{type:'string',pattern:'^\\d{2}:\\d{2}$'},
    timeZone:{type:'string',minLength:1,maxLength:160},taskId:{type:'string',format:'uuid'},
  }}}});
export const followUpInstructions='Use manage_follow_up via EXECUTE for caller callback/reminder requests or cancellations in either direction. Interpret intent and time using the agent prompt. Clear relative requests use delayMinutes and callerConfirmed=true without an evidence quote or another confirmation. For absolute times and cancellations supply current caller evidence and follow the existing proposal/confirmation flow; ask only genuinely missing or ambiguous details. Do not infer a request from an appointment mention. Do not promise completion until scheduled=true/canceled=true. Capacity or low credits may delay dialing. Campaign callbacks consume existing retry allowance. Do not change the caller phone or schedule for someone they mention.';
