import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import {createServer} from 'node:http'; import 'dotenv/config'; import pg from 'pg';
const {createApp}=await import('../src/app.js');const {hashPassword}=await import('../src/auth/password.js');const {closeDatabase}=await import('../src/infrastructure/database.js');const {closeRedis}=await import('../src/infrastructure/redis.js');const {closeQueues}=await import('../src/queues/queue.registry.js');
const db=new pg.Client({connectionString:process.env.DATABASE_URL});const suffix=crypto.randomUUID().slice(0,8);const password=`Task15-${crypto.randomUUID()}!`;const tenants=[];const users=[];const providerIds=[];let phoneId,accountId,server;
async function api(base,path,options={}){return fetch(`${base}${path}`,{...options,headers:{'content-type':'application/json',...(options.headers??{})}})}async function login(base,email){const r=await api(base,'/auth/login',{method:'POST',body:JSON.stringify({email,password})});assert.equal(r.status,200);return(await r.json()).data.accessToken}
async function cleanup(){if(server)await new Promise(r=>server.close(r));if(db._connected){for(const tenant of tenants){const memberUsers=(await db.query('SELECT user_id FROM tenant_memberships WHERE tenant_id=$1',[tenant])).rows.map(x=>x.user_id);users.push(...memberUsers);await db.query('DELETE FROM audit_logs WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM auth_sessions WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM voice_agents WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM phone_number_assignments WHERE tenant_id=$1',[tenant]);await db.query('UPDATE phone_numbers SET assigned_tenant_id=NULL WHERE assigned_tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_memberships WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM company_credit_wallets WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_settings WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_limits WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM workspaces WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM organizations WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenants WHERE id=$1',[tenant]);}
  if(phoneId)await db.query('DELETE FROM phone_numbers WHERE id=$1',[phoneId]);if(accountId)await db.query('DELETE FROM telephony_accounts WHERE id=$1',[accountId]);if(providerIds.length){await db.query('DELETE FROM provider_models WHERE provider_id=ANY($1::uuid[])',[providerIds]);await db.query('DELETE FROM ai_providers WHERE id=ANY($1::uuid[])',[providerIds]);}if(users.length){await db.query('DELETE FROM audit_logs WHERE actor_user_id=ANY($1::uuid[])',[users]);await db.query('DELETE FROM auth_sessions WHERE user_id=ANY($1::uuid[])',[users]);await db.query('DELETE FROM users WHERE id=ANY($1::uuid[])',[users]);}await db.end()}await Promise.allSettled([closeQueues(),closeRedis(),closeDatabase()])}
try{await db.connect();
  const stale=(await db.query("SELECT id FROM tenants WHERE name LIKE 'Task 15 %'")).rows.map(x=>x.id);
  for(const tenant of stale){await db.query('DELETE FROM audit_logs WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM auth_sessions WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM voice_agents WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM phone_number_assignments WHERE tenant_id=$1',[tenant]);await db.query('UPDATE phone_numbers SET assigned_tenant_id=NULL WHERE assigned_tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_memberships WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM company_credit_wallets WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_settings WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenant_limits WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM workspaces WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM organizations WHERE tenant_id=$1',[tenant]);await db.query('DELETE FROM tenants WHERE id=$1',[tenant]);}
  await db.query("DELETE FROM phone_numbers WHERE telephony_account_id IN (SELECT id FROM telephony_accounts WHERE name LIKE 'Task15 %')");await db.query("DELETE FROM telephony_accounts WHERE name LIKE 'Task15 %'");await db.query("DELETE FROM provider_models WHERE provider_id IN (SELECT id FROM ai_providers WHERE name LIKE 'Task15 %')");await db.query("DELETE FROM ai_providers WHERE name LIKE 'Task15 %'");await db.query("DELETE FROM audit_logs WHERE actor_user_id IN (SELECT id FROM users WHERE email::text LIKE 'task15-%@example.test')");await db.query("DELETE FROM auth_sessions WHERE user_id IN (SELECT id FROM users WHERE email::text LIKE 'task15-%@example.test')");await db.query("DELETE FROM users WHERE email::text LIKE 'task15-%@example.test'");
  const adminEmail=`task15-admin-${suffix}@example.test`;const admin=(await db.query(`INSERT INTO users(email,password_hash,first_name,last_name,status,platform_role,email_verified_at)VALUES($1,$2,'Task','Admin','active','super_admin',now())RETURNING id`,[adminEmail,await hashPassword(password)])).rows[0];users.push(admin.id);
  const providerId=(await db.query(`INSERT INTO ai_providers(name,slug,type,status,created_by)VALUES($1,$2,'stt','connected',$3)RETURNING id`,[`Task15 Provider ${suffix}`,`task15-${suffix}`,admin.id])).rows[0].id;providerIds.push(providerId);
  const stt=(await db.query(`INSERT INTO provider_models(provider_id,model_key,display_name,status,created_by)VALUES($1,'stt','STT','active',$2)RETURNING id`,[providerId,admin.id])).rows[0].id;
  const llmProvider=(await db.query(`INSERT INTO ai_providers(name,slug,type,status,created_by)VALUES($1,$2,'llm','connected',$3)RETURNING id`,[`Task15 LLM ${suffix}`,`task15-llm-${suffix}`,admin.id])).rows[0].id;
  const ttsProvider=(await db.query(`INSERT INTO ai_providers(name,slug,type,status,created_by)VALUES($1,$2,'tts','connected',$3)RETURNING id`,[`Task15 TTS ${suffix}`,`task15-tts-${suffix}`,admin.id])).rows[0].id;providerIds.push(llmProvider,ttsProvider);
  const llm=(await db.query(`INSERT INTO provider_models(provider_id,model_key,display_name,status,created_by)VALUES($1,'llm','LLM','active',$2)RETURNING id`,[llmProvider,admin.id])).rows[0].id;const tts=(await db.query(`INSERT INTO provider_models(provider_id,model_key,display_name,status,created_by)VALUES($1,'tts','TTS','active',$2)RETURNING id`,[ttsProvider,admin.id])).rows[0].id;
  server=createServer(createApp());await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve)});const base=`http://127.0.0.1:${server.address().port}`;const adminHeaders={authorization:`Bearer ${await login(base,adminEmail)}`};
  async function company(label){const c=await api(base,'/admin/companies',{method:'POST',headers:adminHeaders,body:JSON.stringify({businessName:`Task 15 ${label} ${suffix}`,email:`task15-${label}-${suffix}@example.test`})});assert.equal(c.status,201);const data=(await c.json()).data;tenants.push(data.tenantId);const email=`task15-dev-${label}-${suffix}@example.test`;assert.equal((await api(base,'/admin/developers',{method:'POST',headers:adminHeaders,body:JSON.stringify({companyId:data.tenantId,fullName:`Developer ${label}`,email,password})})).status,201);return{...data,email,token:await login(base,email)}}
  const a=await company('a');const b=await company('b');accountId=(await db.query(`INSERT INTO telephony_accounts(provider,name,auth_id,auth_token_encrypted,status,created_by)VALUES('plivo',$1,$2,'test','connected',$3)RETURNING id`,[`Task15 ${suffix}`,`task15-${suffix}`,admin.id])).rows[0].id;phoneId=(await db.query(`INSERT INTO phone_numbers(telephony_account_id,e164,status,assigned_tenant_id)VALUES($1,$2,'active',$3)RETURNING id`,[accountId,`+1650${String(Date.now()).slice(-7)}`,a.tenantId])).rows[0].id;await db.query('INSERT INTO phone_number_assignments(phone_number_id,tenant_id,assigned_by)VALUES($1,$2,$3)',[phoneId,a.tenantId,admin.id]);
  const headers={authorization:`Bearer ${a.token}`};const body={name:'Sales Agent',status:'active',phoneNumberId:phoneId,sttModelId:stt,llmModelId:llm,ttsModelId:tts,voiceId:'voice-1',prompt:'You are a helpful sales agent.',settings:{sttMode:'verbatim',ttsSpeed:1}};
  const made=await api(base,'/agents',{method:'POST',headers,body:JSON.stringify(body)});const madePayload=await made.json();assert.equal(made.status,201,JSON.stringify(madePayload));const agent=madePayload.data;assert.equal(agent.stt.modelId,stt);assert.equal(agent.phoneNumberId,phoneId);
  const duplicate=await api(base,'/agents',{method:'POST',headers,body:JSON.stringify({...body,name:'Second Agent'})});assert.equal(duplicate.status,409);
  const userEmail=`task15-user-${suffix}@example.test`;const userMade=await api(base,'/users',{method:'POST',headers,body:JSON.stringify({fullName:'Read Only User',email:userEmail,password})});assert.equal(userMade.status,201);const userHeaders={authorization:`Bearer ${await login(base,userEmail)}`};assert.equal((await api(base,`/agents/${agent.id}`,{headers:userHeaders})).status,200);assert.equal((await api(base,`/agents/${agent.id}`,{method:'PUT',headers:userHeaders,body:JSON.stringify({name:'Forbidden'})})).status,403);
  assert.equal((await api(base,`/agents/${agent.id}`,{headers:{authorization:`Bearer ${b.token}`}})).status,404);const dashboard=await api(base,'/dashboard',{headers});assert.equal((await dashboard.json()).data.metrics.totalAgents,1);
  assert.equal((await api(base,`/agents/${agent.id}`,{method:'DELETE',headers})).status,200);assert.equal((await api(base,`/agents/${agent.id}`,{headers})).status,404);
  console.log(JSON.stringify({success:true,agentCrud:'passed',providerTypeValidation:'passed',phoneTenantMapping:'passed',singleInboundAgentMapping:'passed',companyUserReadOnly:'passed',tenantIsolation:'passed',dashboardAgentMetrics:'passed'},null,2));
}finally{await cleanup()}
