import {z} from 'zod';
const timezone=z.string().trim().min(1).max(64).refine(v=>{try{Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}},'Invalid IANA timezone');
const fields={name:z.string().trim().min(1).max(180),type:z.enum(['batch','realtime']),status:z.enum(['draft','scheduled','running']).default('draft'),agentId:z.string().uuid(),phoneNumberId:z.string().uuid(),timezone:timezone.default('UTC'),concurrencyLimit:z.number().int().min(1).max(20).default(20),priority:z.enum(['low','medium','high']).default('medium'),retries:z.number().int().min(0).max(10).default(0),retryIntervalsMs:z.array(z.number().int().min(1000).max(604800000)).max(10).default([]),retryOutcomes:z.array(z.enum(['busy','failed','no_answer','rejected','unavailable','timeout'])).max(6).default([]).transform(v=>[...new Set(v)]),callingStartTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),callingEndTime:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/),startAfter:z.iso.datetime({offset:true}).nullable().optional(),endAfter:z.iso.datetime({offset:true}).nullable().optional(),contextSchema:z.record(z.string(),z.unknown()).default({})};
function rules(schema){return schema.superRefine((v,c)=>{if(v.retries!==undefined&&v.retryIntervalsMs!==undefined&&v.retryIntervalsMs.length!==v.retries)c.addIssue({code:'custom',path:['retryIntervalsMs'],message:'Provide one interval for each retry'});if(v.callingStartTime&&v.callingEndTime&&v.callingStartTime===v.callingEndTime)c.addIssue({code:'custom',path:['callingEndTime'],message:'Calling start and end times must differ'});if(v.startAfter&&v.endAfter&&new Date(v.endAfter)<=new Date(v.startAfter))c.addIssue({code:'custom',path:['endAfter'],message:'End time must be after start time'});});}
export const createCampaignSchema=rules(z.object(fields));
const updateFields={...fields,status:z.enum(['draft','scheduled','running']),timezone,concurrencyLimit:z.number().int().min(1).max(20),priority:z.enum(['low','medium','high']),retries:z.number().int().min(0).max(10),retryIntervalsMs:z.array(z.number().int().min(1000).max(604800000)).max(10),retryOutcomes:z.array(z.enum(['busy','failed','no_answer','rejected','unavailable','timeout'])).max(6).transform(v=>[...new Set(v)]),contextSchema:z.record(z.string(),z.unknown())};
export const updateCampaignSchema=rules(z.object(updateFields).partial()).refine(v=>Object.keys(v).length>0,'At least one field is required');
export const campaignIdSchema=z.object({campaignId:z.string().uuid()});export const listCampaignsSchema=z.object({search:z.string().trim().max(200).optional(),type:z.enum(['batch','realtime']).optional(),status:z.enum(['draft','scheduled','running','paused','completed','failed','archived']).optional(),page:z.coerce.number().int().min(1).default(1),pageSize:z.coerce.number().int().min(1).max(100).default(20)});
export function parseCampaignInput(s,v){const r=s.safeParse(v);if(r.success)return{success:true,data:r.data};return{success:false,issues:r.error.issues.map(i=>({field:i.path.join('.'),message:i.message}))};}
